name: FlutterwaveSDK CI/CD Workflow

on:
  push:
    branches:
      - dev

jobs:
  build_and_publish:
    name: Build, Test, and Publish
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up CocoaPods
        run: |
          gem install cocoapods
          pod install

      - name: Build Framework
        run: |
          xcodebuild clean build -workspace FlutterwaveSDK.xcworkspace -scheme FlutterwaveSDK_Example -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13"

      - name: Install Dependencies
        run: pod install

      - name: Run Unit Tests
        run: xcodebuild test -workspace FlutterwaveSDK.xcworkspace -scheme FlutterwaveSDK_Example -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13"

      - name: Run Coverage Scan
        run: slather coverage -s --scheme FlutterwaveSDK_Example FlutterwaveSDK.xcodeproj

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Update Podspec Version
        run: |
          # Update the version in your podspec
          sed -i '' "s/s.version *= *'[^']*'/s.version = '$(git describe --tags --abbrev=0 | sed 's/v//')'/g" FlutterwaveSDK.podspec

      - name: Publish to CocoaPods
        run: |
          # Authenticate with CocoaPods repo using environment variables
          echo -e "$POD_REPO_SECRET" | pod trunk register $POD_REPO 'rotimi.joshua@flutterwavego.com' --name='Rotimi Joshua' --silent
          pod trunk push FlutterwaveSDK.podspec --allow-warnings

env:
  POD_REPO: 'https://github.com/CocoaPods/Specs.git'
  POD_REPO_SECRET: ${{ secrets.COCOAPODS_REPO_SECRET }}
